[package]
name = "tidal"
version = "0.1.0"
authors = ["Keith Bingman <keith@keithbingman.com>"]
edition = "2018"

[dependencies]
tide = { git = "https://github.com/rustasync/tide.git" }
http = "0.1"
serde = { version = "1.0.91", features = ["derive"] }
juniper = "0.13.1"
